name: Flutter_Release

on:
  push:
    branches:
      - main 

permissions:
  contents: write  # Grant write access to create a release

jobs:
  build:
    name: Build and Release Flutter App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19  
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Create and Push Git Tag
        run: |
          TAG_NAME=v1.0.${{ github.run_number }}
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          git push origin $TAG_NAME
          git fetch --tags

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: $TAG_NAME  # Use the tag created in the previous step
          release_name: Release $TAG_NAME  # Custom release name, can be omitted for auto generation
          draft: false
          prerelease: false
          generate_release_notes: true  # Automatically generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk  # Ensure correct file path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
