name: Print User Input

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the input message
        run: | 
        echo "User input: '${{ github.event.inputs.message }}' "
